steps:
  - id: 'app-source-code'
    name: 'alpine'
    waitFor: ['-']
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: ['cp', '-T', '-r', '.', '/build/source-code']

  - name: gcr.io/cloud-builders/gsutil
    waitFor:
      - 'app-source-code'
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: ["-m", "rsync", "-p", "-r", "-c", "/build/source-code/wheel-of-misfortune", "gs://wheel-of-misfortune.deliverycenter.com"]
    timeout: "600s"
